### ISSUE TITLE
FatalThrowableError

### ISSUE THREAD

**Issue by Spillo17** [irazasyed/telegram-bot-laravel-starter#1]
Hi,

using your project I'm getting this error:

> Type error: Too few arguments to function Telegram\Bot\Api::setWebhook(), 0 passed in /Applications/MAMP/htdocs/telegram-bot-laravel-starter/app/Http/Controllers/BotController.php on line 44 and exactly 1 expected

do you know why ?

**Comment by irazasyed** [comment]
You need to pass an array with params. Fluent API is no longer supported. This repo wasn't updated with latest changes due to the SDK still in development.
