### ISSUE TITLE
error running composer

### ISSUE THREAD

**Issue by ranrinc** [irazasyed/telegram-bot-laravel-starter#3]
upon running composer.. it hit by this error...Any help??

[InvalidArgumentException]
  Could not find package irazasyed/telegram-bot-laravel-starter with stabilit
  y stable.

**Comment by saber13812002** [comment]
Could not find package irazasyed/telegram-bot-laravel-starter with stability stable.

**Comment by saber13812002** [comment]
finally i can do

1- git clone this_repo
2- make new env file from env.sample
3- run composer i
4- run $ php artisan key:generate
5- run php artisan serve
6- open localhost:8000
